version: '3.8'

services:
   postgres:
      image: postgres:latest
      container_name: url_shortener_postgres
      environment:
         POSTGRES_DB: url_shorten
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
      ports:
         - "5432:5432"
      networks:
         - url_shortener_network

networks:
   url_shortener_network:
      driver: bridge
